### 1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [3]:
import numpy as np

m = np.arange(12).reshape((3,4))
print(m)

print("Number of rows:", m.shape[0])
print("Number of columns:", m.shape[1])

print("Overall mean:", )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Number of rows: 3
Number of columns: 4
